### ISSUE TITLE
Access removed by bot

### ISSUE THREAD

**Issue by Jimbly** [yahoo/memcached-binary#2]
@gyehuda , looks like my access to this repository was automatically removed by some process.  Was I incorrectly removed, or is this going to be a recurring problem?

It looks like I still own the NPM entry, and I've prepared a new repo at https://github.com/Jimbly/memcached-binary , if you think it would be easier to just migrate it out of the Yahoo org, I can just send a pull request that changes the README to indicate where people should send new pull requests.

**Comment by Jimbly** [comment]
Actually, not 100% sure it was a bot, but the email read:

You've been removed from the @Yahoo Inc. organization
Hi @Jimbly,
You've been removed as a collaborator on Yahoo Inc.'s repositories.
You no longer have access to the following repositories:
yahoo/memcached-binary

I believe I received a similar email a couple weeks after leaving the company last year.

**Comment by gyehuda** [comment]
@Jimbly By leaving Yahoo, you get removed from the Yahoo Organization on Github. That's to be expected. I can add you back in as an outside contributor. 

Also, we are enforcing the rule that people with privileges on our repos also have 2 factor authentication turned on. This protects the project (and you probably want to protect your account anyways). So yesterday's may have been a result of that sweep.

I'll invite you back in as an outside collaborator (since technically you now are), and ask that you set up 2FA on your account.  All the best.

**Comment by Jimbly** [comment]
I did not have 2-factor auth set (didn't even know it was an option here : ), I have enabled that and rejoined the repo, hopefully it sticks, thanks =).
